import { Agent } from '../types/agent';

export const generateManifest = (agent: Agent): string => {
  return `# OASF Agent Record (schema_version: 1.0.0)
name: "${agent.name}"
description: "${agent.shortDescription}"
version: "${agent.version}"
schema_version: "1.0.0"
authors:
  - "Prodapt Agent Hub <agent-hub@prodapt.com>"
created_at: "${agent.createdDate}T00:00:00Z"

domains:
  - name: "${agent.businessDomain.toLowerCase().replace(/ /g, '_')}"
    id: ${agent.name.length * 123}

modules:
  - name: "integration/agentspec"
    data:
      config:
        type: "url"
        urls:
          - "https://agent-hub.prodapt.com/agentspec/${agent.id}.yaml"
      deployment_options:
        - name: "prodapt-native"
          runtime_framework: "langgraph"

  - x_agent_deployment:
      agent_id: "${agent.id}"
      capabilities:
        operations:
          ${agent.goals.map(goal => `- "${goal}"`).join('\n          ')}

      security:
        controls:
          ${agent.securityControls.map(ctrl => `- "${ctrl}"`).join('\n          ')}

      targets:
        - id: "prodapt-enterprise-cloud"
          type: "platform"
          platform: "Prodapt"
`;
};

export const generateAgentCardMarkdown = (agent: Agent): string => {
  return `# Agent Card: ${agent.name}

## Overview
**ID:** ${agent.id}
**Domain:** ${agent.businessDomain}
**Status:** ${agent.status}
**Version:** ${agent.version}

## Description
${agent.shortDescription}

## Problem Statement & Features
${agent.problemStatement}

## Goals & Objectives
${agent.goals.map(goal => `- ${goal}`).join('\n')}

## Scope
### In Scope
${agent.inScope.map(item => `- ${item}`).join('\n')}

### Out of Scope
${agent.outOfScope.map(item => `- ${item}`).join('\n')}

## Operational Details
${agent.operationalDetails}

## Technical Details
### Inputs
${agent.inputs.map(i => `- ${i}`).join('\n')}

### Outputs
${agent.outputs.map(o => `- ${o}`).join('\n')}

### Tools & Technologies
${agent.tools.map(t => `- **${t.name}**: ${t.description}`).join('\n')}

## Performance Indices (KPIs)
${agent.kpis.map(kpi => `- **${kpi.name}**: Target: ${kpi.target}`).join('\n')}

## Security Controls
${agent.securityControls.map(ctrl => `- ${ctrl}`).join('\n')}

---
*Generated by Prodapt Agent HUB Deployment Engine*
`;
};
